deploy:
  runs-on: ubuntu-latest
  needs: build
  permissions:
    id-token: write #This is required for requesting the JWT
    contents: read #This is required for actions/checkout

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FBFDD5D1898F46619781EAEEC6BE828D }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_582FD4701C594AB1A7E749E9D7F60A46 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE35CCFFB5C7447A8A095400745056C3 }}

    - name: Stop Azure Web App before deployment
      run: |
        az webapp stop --name Sample-net8 --resource-group <YourResourceGroupName>

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Sample-net8'
        slot-name: 'Production'
        package: .

    - name: Start Azure Web App after deployment
      run: |
        az webapp start --name Sample-net8 --resource-group <YourResourceGroupName>
